# Generated by Django 4.2.7 on 2023-11-09 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=150)),
                ('classDescription', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=250)),
                ('questionDescription', models.CharField(max_length=250)),
                ('optionA', models.CharField(max_length=250)),
                ('optionB', models.CharField(max_length=250)),
                ('optionC', models.CharField(max_length=250)),
                ('optionD', models.CharField(max_length=250)),
                ('correctAnswer', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='userID',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='user_id',
            new_name='userID',
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicTitle', models.CharField(max_length=150)),
                ('topicDescription', models.CharField(max_length=250)),
                ('classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizTitle', models.CharField(max_length=150)),
                ('quizDescription', models.CharField(max_length=250)),
                ('timeLimit', models.IntegerField()),
                ('totalScore', models.IntegerField()),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.topics')),
            ],
        ),
        migrations.CreateModel(
            name='QuizRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeTaken', models.DateTimeField(auto_now_add=True)),
                ('timeLeft', models.IntegerField()),
                ('score', models.IntegerField()),
                ('quizID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.quizzes')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.student')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qbank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.questionbank')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.quizzes')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='teacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.teacher'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250)),
                ('isCorrect', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.question')),
                ('quizRecord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.quizrecord')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.student')),
            ],
        ),
    ]
