# Generated by Django 4.2.7 on 2023-11-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_student_userid_student_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='userType',
        ),
    ]
