# Generated by Django 4.2.7 on 2023-11-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_usertype_student_userid_alter_teacher_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='students/'),
        ),
    ]
