# Generated by Django 4.2.7 on 2023-11-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question_id',
            new_name='questionID',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='quizRecord_id',
            new_name='quizRecordID',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='student_id',
            new_name='studentID',
        ),
    ]
