# Generated by Django 4.2.7 on 2023-11-10 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_question_id_answers_questionid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='studentID',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='questions',
            field=models.ManyToManyField(to='web.question'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='questionID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.question'),
        ),
        migrations.AlterField(
            model_name='quizrecord',
            name='studentID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.student'),
        ),
    ]
